# Generated by Django 4.0 on 2022-01-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='support',
            field=models.BooleanField(default=False, verbose_name='Саппорт специалист'),
        ),
    ]
