# Generated by Django 4.0 on 2022-01-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_staff_alter_user_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Стафф'),
        ),
    ]
