# Generated by Django 4.0 on 2021-12-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickets',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='level',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='tickets',
            name='client',
            field=models.ForeignKey(limit_choices_to={'support': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='users.user'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='star_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'In waiting'), (1, 'In works'), (2, 'Done')], default=0),
        ),
        migrations.AddField(
            model_name='tickets',
            name='support_ticket',
            field=models.ForeignKey(limit_choices_to={'support': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='users.user'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
