# Generated by Django 4.0 on 2022-01-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_tickets_options_remove_tickets_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickets',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Тикет', 'verbose_name_plural': 'Тикеты'},
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='slug',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'In waiting'), (1, 'In works'), (2, 'Done')], default=0, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок тикета'),
        ),
    ]
