# Generated by Django 4.0 on 2022-01-06 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_staff'),
        ('tickets', '0003_alter_tickets_options_remove_tickets_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='client',
            field=models.ForeignKey(limit_choices_to={'support': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='users.user', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='support_ticket',
            field=models.ForeignKey(limit_choices_to={'support': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='users.user', verbose_name='Специалист'),
        ),
    ]
