# Generated by Django 4.0 on 2022-01-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_tickets_client_alter_tickets_support_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок тикета'),
        ),
    ]
